### ISSUE TITLE
Why lots of 429 Network error during my running? And how can I deal with it...

### ISSUE THREAD

**Issue by LeeOrange-is-me** [X-PLUG/MobileAgent#19]
```APL
Action: click icon (three vertical dots, top right, center)
一轮操作
ACT: tap (993,599)
请求了一次
Network Error:
<Response [429]>
Network Error:
<Response [429]>
Network Error:
<Response [429]>
Network Error:
<Response [429]>
Network Error:
<Response [429]>
Network Error:
<Response [429]>
Network Error:
<Response [429]>
```
First, I know that 429 means request too frequently during a short time.
But  I wanna to know,  is there only me having encounter with this error? And how can I deal with it?

**Comment by junyangwang0410** [comment]
> ```apl
> Action: click icon (three vertical dots, top right, center)
> 一轮操作
> ACT: tap (993,599)
> 请求了一次
> Network Error:
> <Response [429]>
> Network Error:
> <Response [429]>
> Network Error:
> <Response [429]>
> Network Error:
> <Response [429]>
> Network Error:
> <Response [429]>
> Network Error:
> <Response [429]>
> Network Error:
> <Response [429]>
> ```
> 
> First, I know that 429 means request too frequently during a short time. But I wanna to know, is there only me having encounter with this error? And how can I deal with it?

It may be useful to try adding time.sleep(10) in each iteration. But I'm more concerned if it's because your API has stricter speed limits. 

And I recommend you print(response.json()) in MobileAgent/api.py to see the specific reason. Because there may be other restrictions (such as daily token limit).
