### ISSUE TITLE
MobileAgent使用GPT-4o

### ISSUE THREAD

**Issue by cpken** [X-PLUG/MobileAgent#20]
使用 [MobileAgent](https://github.com/X-PLUG/MobileAgent) 测试一些功能，

    gpt-4o
    python 3.10
    openai 1.30
    base_url: https://api.nextapi.fun/v1/chat/completions

在运行后，发现返回结果为空，仅请求成功而已，

```python
res = requests.post(api_url, headers=headers, json=data)
print('================= res-start: =============')
print(res.status_code)
if res.status_code == 200:
    print('请求成功:', res.text)
    print('content:', res.content)
print('================= res-end: ==============')
res = res.json()['choices'][0]['message']['content']
```

```
================= res-start: =============
<Response [200]>
200
请求成功: json{}

content: b'json\n{}\n'
================= res-end: ==============
```

步骤

- 安装好 [MobileAgent](https://github.com/X-PLUG/MobileAgent)
- 更改 MobileAgent/api.py 中 api_url = "https://api.nextapi.fun/v1/chat/completions"
- 运行 run.py

执行结果

应该正确返回 json 内容，但却返回的是空 json。

![334632865-55015af8-e29e-4174-9278-ac3f53d1dc5c](https://github.com/X-PLUG/MobileAgent/assets/38244430/eeceb084-9cb5-41d5-90a7-f5c5ffea2d85)

**Comment by 17603127956** [comment]
请问应该如何修改，遇到了同样的问题

**Comment by cpken** [comment]
图片太大了。

**Comment by junyangwang0410** [comment]
> 请问应该如何修改，遇到了同样的问题

可以用压缩率较高的图片格式例如jpg、jpeg等，不要改变图片分辨率

**Comment by 17603127956** [comment]
> > 请问应该如何修改，遇到了同样的问题
> 
> 可以用压缩率较高的图片格式例如jpg、jpeg等，不要改变图片分辨率

谢谢

**Comment by 17603127956** [comment]
> jpeg

麻烦请教一下大佬，图片大小为多少可以成功，咱们使用的是相同的API，目前压缩图片到60KB还没有上传成功，依旧报错。感谢！

**Comment by 17603127956** [comment]
> 图片太大了。

麻烦请教一下大佬，图片大小为多少可以成功，咱们使用的是相同的API，目前压缩图片到60KB还没有上传成功，依旧报错。感谢！

**Comment by junyangwang0410** [comment]
> > 图片太大了。
> 
> 麻烦请教一下大佬，图片大小为多少可以成功，咱们使用的是相同的API，目前压缩图片到60KB还没有上传成功，依旧报错。感谢！

报错信息可以发一下吗？我理解如果是图片太大的问题，是可以返回200的

**Comment by 17603127956** [comment]
> > > 图片太大了。
> > 
> > 
> > 麻烦请教一下大佬，图片大小为多少可以成功，咱们使用的是相同的API，目前压缩图片到60KB还没有上传成功，依旧报错。感谢！
> 
> 报错信息可以发一下吗？我理解如果是图片太大的问题，是可以返回200的

![screenshot](https://github.com/user-attachments/assets/b57c05ed-8eaa-45b6-bb03-caa8d42abef2)
这是我测试的图片。
报错信息：
================= res-start: =============
200
请求成功: ```json
{}
```
请求数据：
[请求数据.txt](https://github.com/user-attachments/files/16279703/default.txt)

content: b'```json\n{}\n```'

**Comment by 17603127956** [comment]
> > > 图片太大了。
> > 
> > 
> > 麻烦请教一下大佬，图片大小为多少可以成功，咱们使用的是相同的API，目前压缩图片到60KB还没有上传成功，依旧报错。感谢！
> 
> 报错信息可以发一下吗？我理解如果是图片太大的问题，是可以返回200的

测试的图片：
![screenshot](https://github.com/user-attachments/assets/0c414a04-08ca-4665-89cc-92af9c1b0662)

测试的返回结果：
================= res-start: =============
200
请求成功: ```json
{}
```
content: b'```json\n{}\n```'
=================================

请求参数：
[请求数据.txt](https://github.com/user-attachments/files/16279750/default.txt)

**Comment by 17603127956** [comment]
> > > > 图片太大了。
> > > 
> > > 
> > > 麻烦请教一下大佬，图片大小为多少可以成功，咱们使用的是相同的API，目前压缩图片到60KB还没有上传成功，依旧报错。感谢！
> > 
> > 
> > 报错信息可以发一下吗？我理解如果是图片太大的问题，是可以返回200的
> 
> 测试的图片： ![screenshot](https://private-user-images.githubusercontent.com/112071396/349868573-0c414a04-08ca-4665-89cc-92af9c1b0662.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTA1MzEsIm5iZiI6MTcyMTI5MDIzMSwicGF0aCI6Ii8xMTIwNzEzOTYvMzQ5ODY4NTczLTBjNDE0YTA0LTA4Y2EtNDY2NS04OWNjLTkyYWY5YzFiMDY2Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwODEwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzlmMDliNTAyNDljNjM0NDViZjRlMGNkZjEzZDExMWVjMGZjZWFlYjM2MjU5MmZiMTU4MmYzMDc4YmYzZTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WE2OmVx2em4QRFglhSt_gIIbF0kUFa9pP-htRwibXao)
> 
> 测试的返回结果： ================= res-start: ============= 200 请求成功: ```json {}
> 
> ```
> content: b'```json\n{}\n```'
> =================================
> 
> 请求参数：
> [请求数据.txt](https://github.com/user-attachments/files/16279750/default.txt)
> ```

但是同样的截图，我在魔塔社区页面上测试是可以执行的，很奇怪

**Comment by junyangwang0410** [comment]
> > > > > 图片太大了。
> > > > 
> > > > 
> > > > 麻烦请教一下大佬，图片大小为多少可以成功，咱们使用的是相同的API，目前压缩图片到60KB还没有上传成功，依旧报错。感谢！
> > > 
> > > 
> > > 报错信息可以发一下吗？我理解如果是图片太大的问题，是可以返回200的
> > 
> > 
> > 测试的图片： ![screenshot](https://private-user-images.githubusercontent.com/112071396/349868573-0c414a04-08ca-4665-89cc-92af9c1b0662.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTA1MzEsIm5iZiI6MTcyMTI5MDIzMSwicGF0aCI6Ii8xMTIwNzEzOTYvMzQ5ODY4NTczLTBjNDE0YTA0LTA4Y2EtNDY2NS04OWNjLTkyYWY5YzFiMDY2Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwODEwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzlmMDliNTAyNDljNjM0NDViZjRlMGNkZjEzZDExMWVjMGZjZWFlYjM2MjU5MmZiMTU4MmYzMDc4YmYzZTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WE2OmVx2em4QRFglhSt_gIIbF0kUFa9pP-htRwibXao)
> > 测试的返回结果： ================= res-start: ============= 200 请求成功: ```json {}
> > ```
> > content: b'```json\n{}\n```'
> > =================================
> > 
> > 请求参数：
> > [请求数据.txt](https://github.com/user-attachments/files/16279750/default.txt)
> > ```
> 
> 但是同样的截图，我在魔塔社区页面上测试是可以执行的，很奇怪

那我想可能是你这边的API存在问题了。可以试试其他图片会不会返回空回复。

**Comment by 17603127956** [comment]
> > > > > > 图片太大了。
> > > > > 
> > > > > 
> > > > > 麻烦请教一下大佬，图片大小为多少可以成功，咱们使用的是相同的API，目前压缩图片到60KB还没有上传成功，依旧报错。感谢！
> > > > 
> > > > 
> > > > 报错信息可以发一下吗？我理解如果是图片太大的问题，是可以返回200的
> > > 
> > > 
> > > 测试的图片： ![screenshot](https://private-user-images.githubusercontent.com/112071396/349868573-0c414a04-08ca-4665-89cc-92af9c1b0662.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTA1MzEsIm5iZiI6MTcyMTI5MDIzMSwicGF0aCI6Ii8xMTIwNzEzOTYvMzQ5ODY4NTczLTBjNDE0YTA0LTA4Y2EtNDY2NS04OWNjLTkyYWY5YzFiMDY2Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwODEwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzlmMDliNTAyNDljNjM0NDViZjRlMGNkZjEzZDExMWVjMGZjZWFlYjM2MjU5MmZiMTU4MmYzMDc4YmYzZTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WE2OmVx2em4QRFglhSt_gIIbF0kUFa9pP-htRwibXao)
> > > 测试的返回结果： ================= res-start: ============= 200 请求成功: ```json {}
> > > ```
> > > content: b'```json\n{}\n```'
> > > =================================
> > > 
> > > 请求参数：
> > > [请求数据.txt](https://github.com/user-attachments/files/16279750/default.txt)
> > > ```
> > 
> > 
> > 但是同样的截图，我在魔塔社区页面上测试是可以执行的，很奇怪
> 
> 那我想可能是你这边的API存在问题了。可以试试其他图片会不会返回空回复。

的确是API的问题，更换API后解决，感谢！
