### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by bluelion8226** [X-PLUG/MobileAgent#21]
Hi,
I get the following error message:

ImportError: cannot import name '_datasets_server' from 'datasets.utils' 

PS:
Name: datasets
Version: 2.19.2

Any ideas how to fix this?

Thank you.

**Comment by junyangwang0410** [comment]
> Hi, I get the following error message:
> 
> ImportError: cannot import name '_datasets_server' from 'datasets.utils'
> 
> PS: Name: datasets Version: 2.19.2
> 
> Any ideas how to fix this?
> 
> Thank you.

Hello, can you provide more complete error information?
