### ISSUE TITLE
GroundingDINO报错：BoxAnnotator.annotate() got an unexpected keyword argument 'labels'

### ISSUE THREAD

**Issue by zqxuturbo** [X-PLUG/MobileAgent#33]
python 3.10的环境，这个错误有人遇到吗？

**Comment by zqxuturbo** [comment]
版本不匹配，安装老版本的supervision就可以了

**Comment by junyangwang0410** [comment]
> 版本不匹配，安装老版本的supervision就可以了

确实存在这个问题，我们已经在requirements.txt中修改为supervision的0.21.0版本
