### ISSUE TITLE
Error when doing action 'type'

### ISSUE THREAD

**Issue by lln556** [X-PLUG/MobileAgent#51]
<img width="565" alt="image" src="https://github.com/user-attachments/assets/5b44ff83-2ff2-4381-bcdc-24f520762370">

**Comment by junyangwang0410** [comment]
An unexpected situation occurred here, that is, the agent did not output according to the format, resulting in string parsing failure. You can add exception detection code and retry after detecting the exception to solve the problem. Generally, this situation is very accidental. Also, if you are not using gpt-4o (which has strong instruction following capabilities), this situation may easily occur.
