### ISSUE TITLE
我使用安卓模拟器，获得屏幕截图和操作指令都没有问题，但是就是发不出tap的adb命令，这是为什么？

### ISSUE THREAD

**Issue by herist** [X-PLUG/MobileAgent#52]
res_content:
### Thought ###
The user has requested to open the app named "浏览器" (Browser). The app icon for "浏览器" is located at coordinates [660, 717].

### Action ###
Open app (浏览器)

### Operation ###
Opening the app named "浏览器" (Browser).
res_content:
### Thought ###
The user has requested to open the app named "浏览器" (Browser). The app icon for "浏览器" is located at coordinates [660, 717].

### Action ###
Open app (浏览器)

### Operation ###
Opening the app named "浏览器" (Browser).

手动触发点击命令是ok的
adb shell input tap 660 717

![image](https://github.com/user-attachments/assets/ec209ba0-f118-4dfc-b233-c64bafaf68a7)

但是代理程序，无法执行这个命令，何解？

run.py中

# You can add operational knowledge to help Agent operate more accurately.
add_info = ("If you want to tap an icon of an app, use the action \"Open app\". If you want to exit an app, use the action \"Home\"."
            "我的手机是中文语言的，请打开名称为浏览器的app")

**Comment by junyangwang0410** [comment]
如果是小米的产品（包括红米），需要额外打开一个操作权限，同样在开发者选项中

**Comment by junyangwang0410** [comment]
open这个操作本质上也是点击本文，如果你手机桌面上没有浏览器，请把浏览器放到当前桌面；如果已经放到当前页面，则我猜测你的设备中浏览器下方没有app的名字，或者点击图标下方的app名字无法打开app。

**Comment by junyangwang0410** [comment]
> open这个操作本质上也是点击本文，如果你手机桌面上没有浏览器，请把浏览器放到当前桌面；如果已经放到当前页面，则我猜测你的设备中浏览器下方没有app的名字，或者点击图标下方的app名字无法打开app。

你可以检查上述问题描述，并回复你当前的情况，便于我为你提供解决方案

**Comment by herist** [comment]
感谢答复，是修改代码没注意导致的

**Comment by herist** [comment]
感谢答复，是修改代码没注意导致的
