### ISSUE TITLE
各位大佬，都支持安卓哪些版本呀？

### ISSUE THREAD

**Issue by shenyugub** [X-PLUG/MobileAgent#53]
我的手机版本是安卓14，USB调试模式和ADB模式都打开了，但现在电脑通过adb发现不了设备
![image](https://github.com/user-attachments/assets/b2c954e1-ec9c-4d38-910a-94194a6312de)

**Comment by junyangwang0410** [comment]
可能也跟电脑有关系，之前我也遇到过这种情况，但是换一台电脑就可以了，希望对你有帮助
