### ISSUE TITLE
除了数据线直连手机，还有其他方式吗

### ISSUE THREAD

**Issue by shenyugub** [X-PLUG/MobileAgent#54]
各位大佬，除了数据线直连手机，还有其他方式连接手机吗？比如通过同一个WIFI？@junyangwang0410

**Comment by junyangwang0410** [comment]
> 各位大佬，除了数据线直连手机，还有其他方式连接手机吗？比如通过同一个WIFI？@junyangwang0410

很多手机都支持无线ADB调试，你可以查找一下相关资料，如果成功了也欢迎把教程pr到代码仓库，给开发者更多选择
