### ISSUE TITLE
请教大佬：AssertionError: Torch not compiled with CUDA enabled这个问题怎么解决

### ISSUE THREAD

**Issue by shenyugub** [X-PLUG/MobileAgent#60]
当前环境：NVIDIA-SMI 475.14       Driver Version: 475.14       CUDA Version: 11.4  
Python版本：3.10.11
![image](https://github.com/user-attachments/assets/cb44d776-65cd-4b04-9205-8d9758907167)

**Comment by junyangwang0410** [comment]
安装GPU版本的torch即可，需要对应你的CUDA版本，例如你可以安装torch x.x.x+cu114，可以pip show torch查看你的版本是否是GPU版本，如果没有后缀则可能是安装的CPU版本
