### ISSUE TITLE
icon描述返回的结果全部都是This is an icon.

### ISSUE THREAD

**Issue by lgy0404** [X-PLUG/MobileAgent#79]
![image](https://github.com/user-attachments/assets/f0232eeb-cabd-4f4b-bec7-289c89aad118)

**Comment by junyangwang0410** [comment]
这是由于icon caption模型调用失败了，返回了兜底的结果

**Comment by lgy0404** [comment]
> 这是由于icon caption模型调用失败了，返回了兜底的结果

好的~现在解决了谢谢！
